modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="collaborationmod"
version="1.0.0"
displayName="CollaborationMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="iccelerox, MCreator"

[[dependencies.collaborationmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



